// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalEdu_Repositories.Models;

public partial class SurveyOption
{
    public Guid Id { get; set; }

    public Guid SurveyId { get; set; }

    public string Answer { get; set; }

    public int Points { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Survey Survey { get; set; }
}